services:
  - type: web
    name: library-management-system
    runtime: java
    repo: https://github.com/Rishi-1601/library-management-system
    branch: main
    rootDir: backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
